apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-admin
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: spring-boot-admin
    spec:
      containers:
        - name: spring-boot-admin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080