apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  selector:
    matchLabels:
      app: kafka-consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: kafka-demo/kafka-consumer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-svc
spec:
  selector:
    app: kafka-consumer
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 30002
  type: NodePort